# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[39,)" 
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="LGPL 3.0"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The modid of the mod
modId="goldenglitter"
# The version number of the mod
version="${file.jarVersion}"
 # A display name for the mod
displayName="akkamaddi's Golden Glitter"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Created by akkamaddi, reliant on AleXndrTheGr8st, maintained by Sinhika"
# A text field displayed in the mod UI
authors="akkamaddi, Sinhika" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Four gold alloys, plus a self-powered rail.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.goldenglitter]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.goldenglitter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.18.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goldenglitter]]
    modId="simplecorelib"
    mandatory=true
    versionRange="[1.18.1-4.0.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goldenglitter]]
    modId="simpleores"
    mandatory=true
    versionRange="[[1.18.1-4.0.0.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goldenglitter]]
    modId="fusion"
    mandatory=true
    versionRange="[[1.18.1-4.0.1.0, )"
    ordering="NONE"
    side="BOTH"
